spring.application.name=backend
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/extension_observatory
spring.datasource.username=postgres
spring.datasource.password=kriti@982
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect